In [39]:
import pandas as pd
# Load dataset
df = pd.read_csv("data/appointsments_data.csv")
df.head()

,appointment_id,slot_id,scheduling_date,appointment_date,scheduling_interval,status,check_in_time,appointment_duration,start_time,end_time,waiting_time,patient_id,sex,age,age_group
0,138,1,28-12-2014,01-01-2015 08:00,4,did not attend,NaN,NaN,NaN,NaN,NaN,8285,Male,37,35-39
1,146,23,29-12-2014,01-01-2015 13:30,3,did not attend,NaN,NaN,NaN,NaN,NaN,5972,Male,84,80-84
2,21,24,17-12-2014,01-01-2015 13:45,15,attended,13:36:45,5.2,13:37:57,13:43:09,1.2,6472,Male,77,75-79
3,233,25,31-12-2014,01-01-2015 14:00,1,attended,13:59:32,28.9,14:00:40,14:29:34,1.1,5376,Female,37,35-39
4,90,26,26-12-2014,01-01-2015 14:15,6,cancelled,NaN,NaN,NaN,NaN,NaN,8028,Male,72,70-74

In [40]:
df.shape

(111488, 15)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111488 entries, 0 to 111487
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   appointment_id        111488 non-null  int64
 1   slot_id               111488 non-null  int64
 2   scheduling_date       111488 non-null  object
 3   appointment_date      111488 non-null  object
 4   scheduling_interval   111488 non-null  int64
 5   status                111488 non-null  object
 6   check_in_time         86032 non-null   object
 7   appointment_duration  86032 non-null   float64
 8   start_time            86032 non-null   object
 9   end_time              86032 non-null   object
 10  waiting_time          86032 non-null   float64
 11  patient_id            111488 non-null  int64
 12  sex                   111488 non-null  object
 13  age                   111488 non-null  int64
 14  age_group             111488 non-null  object
dtypes: float64(2), int64(5), object(8)
memory usage: 12.8+ MB

In [42]:
# Convert datetime
df["appointment_date"] = pd.to_datetime(
    df["appointment_date"],
    format="%d-%m-%Y %H:%M"
)

In [43]:
# Convert datetime
df["scheduling_date"] = pd.to_datetime(
    df["scheduling_date"],
    format="%d-%m-%Y"
)

In [44]:
# Extract datetime information
df["Date"] = df["appointment_date"].dt.date
df["Hour"] = df["appointment_date"].dt.hour
df["Weekday"] = df["appointment_date"].dt.day_name()
df["Month"] = df["appointment_date"].dt.month_name()
df.head()

,appointment_id,slot_id,scheduling_date,appointment_date,scheduling_interval,status,check_in_time,appointment_duration,start_time,end_time,waiting_time,patient_id,sex,age,age_group,Date,Hour,Weekday,Month
0,138,1,2014-12-28,2015-01-01 08:00:00,4,did not attend,NaN,NaN,NaN,NaN,NaN,8285,Male,37,35-39,2015-01-01,8,Thursday,January
1,146,23,2014-12-29,2015-01-01 13:30:00,3,did not attend,NaN,NaN,NaN,NaN,NaN,5972,Male,84,80-84,2015-01-01,13,Thursday,January
2,21,24,2014-12-17,2015-01-01 13:45:00,15,attended,13:36:45,5.2,13:37:57,13:43:09,1.2,6472,Male,77,75-79,2015-01-01,13,Thursday,January
3,233,25,2014-12-31,2015-01-01 14:00:00,1,attended,13:59:32,28.9,14:00:40,14:29:34,1.1,5376,Female,37,35-39,2015-01-01,14,Thursday,January
4,90,26,2014-12-26,2015-01-01 14:15:00,6,cancelled,NaN,NaN,NaN,NaN,NaN,8028,Male,72,70-74,2015-01-01,14,Thursday,January

In [45]:
# Set datetime index
df = df.set_index("appointment_date")

In [46]:
# Sort
df = df.sort_index()

In [47]:
# Appointments on 5 Nov
print(df.loc["2024-11-05"])

                     appointment_id  slot_id scheduling_date  \
appointment_date
2024-11-05 08:00:00          110423   102721      2024-10-26
2024-11-05 08:15:00          110718   102722      2024-11-04
2024-11-05 08:30:00          110395   102723      2024-10-25
2024-11-05 08:45:00          110061   102724      2024-10-14
2024-11-05 09:00:00          110641   102725      2024-11-02
2024-11-05 09:00:00          110504   102725      2024-10-28
2024-11-05 09:15:00          110577   102726      2024-10-31
2024-11-05 09:30:00          110659   102727      2024-11-03
2024-11-05 09:45:00          110601   102728      2024-11-01
2024-11-05 10:00:00          110683   102729      2024-11-03
2024-11-05 10:15:00          110488   102730      2024-10-28
2024-11-05 10:30:00          110510   102731      2024-10-29
2024-11-05 10:45:00          110554   102732      2024-10-30
2024-11-05 11:00:00          110362   102733      2024-10-24
2024-11-05 11:15:00          110468   102734      2024-10-28
2024-11-05 11:30:00          110434   102735      2024-10-26
2024-11-05 11:45:00          110716   102736      2024-11-04
2024-11-05 12:00:00          110632   102737      2024-11-02
2024-11-05 12:15:00          110692   102738      2024-11-03
2024-11-05 12:30:00          110697   102739      2024-11-03
2024-11-05 12:45:00          110653   102740      2024-11-03
2024-11-05 13:00:00          110354   102741      2024-10-23
2024-11-05 13:15:00          110460   102742      2024-10-27
2024-11-05 13:15:00          110371   102742      2024-10-24
2024-11-05 13:30:00          110672   102743      2024-11-03
2024-11-05 13:30:00          110587   102743      2024-10-31
2024-11-05 13:45:00          110708   102744      2024-11-04
2024-11-05 14:00:00          110288   102745      2024-10-21
2024-11-05 14:15:00          110416   102746      2024-10-25
2024-11-05 14:30:00          110432   102747      2024-10-26
2024-11-05 14:45:00          110652   102748      2024-11-03
2024-11-05 15:00:00          110467   102749      2024-10-28
2024-11-05 15:15:00          110191   102750      2024-10-18
2024-11-05 15:30:00          110664   102751      2024-11-03
2024-11-05 15:30:00          110614   102751      2024-11-01
2024-11-05 15:45:00          110703   102752      2024-11-04
2024-11-05 16:00:00          110355   102753      2024-10-23
2024-11-05 16:15:00          110543   102754      2024-10-30
2024-11-05 16:30:00          110598   102755      2024-11-01
2024-11-05 16:45:00          110502   102756      2024-10-28
2024-11-05 17:00:00          110676   102757      2024-11-03
2024-11-05 17:15:00          110396   102758      2024-10-25
2024-11-05 17:30:00          110527   102759      2024-10-29
2024-11-05 17:45:00          110570   102760      2024-10-31

                     scheduling_interval          status check_in_time  \
appointment_date
2024-11-05 08:00:00                   10        attended      07:43:18
2024-11-05 08:15:00                    1        attended      08:10:21
2024-11-05 08:30:00                   11        attended      08:12:37
2024-11-05 08:45:00                   22        attended      08:51:20
2024-11-05 09:00:00                    3       cancelled           NaN
2024-11-05 09:00:00                    8       cancelled           NaN
2024-11-05 09:15:00                    5        attended      08:44:11
2024-11-05 09:30:00                    2        attended      09:18:57
2024-11-05 09:45:00                    4        attended      09:39:21
2024-11-05 10:00:00                    2        attended      09:43:46
2024-11-05 10:15:00                    8        attended      09:47:55
2024-11-05 10:30:00                    7        attended      10:21:23
2024-11-05 10:45:00                    6        attended      10:28:26
2024-11-05 11:00:00                   12        attended      11:02:18
2024-11-05 11:15:00                    8        attended      11:13:30
2024-11-05 11:30:00                   10        attended      11:25:00
2024-11-05 11:45:00                    1        attended      11:43:57
2024-11-05 12:00:00                    3        attended      11:59:32
2024-11-05 12:15:00                    2        attended      11:58:47
2024-11-05 12:30:00                    2        attended      12:03:39
2024-11-05 12:45:00                    2        attended      12:39:24
2024-11-05 13:00:00                   13        attended      13:08:13
2024-11-05 13:15:00                    9  did not attend           NaN
2024-11-05 13:15:00                   12       cancelled           NaN
2024-11-05 13:30:00                    2        attended      13:42:21
2024-11-05 13:30:00                    5       cancelled           NaN
2024-11-05 13:45:00                    1        attended      13:26:50
2024-11-05 14:00:00                   15        attended      13:38:49
2024-11-05 14:15:00                   11       cancelled           NaN
2024-11-05 14:30:00                   10        attended      14:07:39
2024-11-05 14:45:00                    2       cancelled           NaN
2024-11-05 15:00:00                    8        attended      14:55:52
2024-11-05 15:15:00                   18        attended      15:02:11
2024-11-05 15:30:00                    2        attended      15:26:14
2024-11-05 15:30:00                    4       cancelled           NaN
2024-11-05 15:45:00                    1       cancelled           NaN
2024-11-05 16:00:00                   13        attended      15:55:29
2024-11-05 16:15:00                    6        attended      16:08:54
2024-11-05 16:30:00                    4  did not attend           NaN
2024-11-05 16:45:00                    8        attended      16:39:55
2024-11-05 17:00:00                    2        attended      17:09:32
2024-11-05 17:15:00                   11        attended      17:13:30
2024-11-05 17:30:00                    7        attended      17:14:05
2024-11-05 17:45:00                    5        attended      17:36:07

                     appointment_duration start_time  end_time  waiting_time  \
appointment_date
2024-11-05 08:00:00                  15.8   08:00:53  08:16:41          17.6
2024-11-05 08:15:00                   9.3   08:17:52  08:27:10           7.5
2024-11-05 08:30:00                   3.9   08:28:08  08:32:02          15.5
2024-11-05 08:45:00                  11.2   09:14:53  09:26:05          23.6
2024-11-05 09:00:00                   NaN        NaN       NaN           NaN
2024-11-05 09:00:00                   NaN        NaN       NaN           NaN
2024-11-05 09:15:00                  28.7   08:45:13  09:13:55           1.0
2024-11-05 09:30:00                  26.1   09:26:56  09:53:02           8.0
2024-11-05 09:45:00                  10.1   09:53:58  10:04:04          14.6
2024-11-05 10:00:00                  23.6   10:05:16  10:28:52          21.5
2024-11-05 10:15:00                  37.1   10:29:47  11:06:53          41.9
2024-11-05 10:30:00                  27.7   11:08:03  11:35:45          46.7
2024-11-05 10:45:00                   4.1   11:36:25  11:40:31          68.0
2024-11-05 11:00:00                   9.1   11:41:25  11:50:31          39.1
2024-11-05 11:15:00                  21.8   11:51:39  12:13:27          38.2
2024-11-05 11:30:00                  44.0   12:14:34  12:58:34          49.6
2024-11-05 11:45:00                  12.5   12:59:38  13:12:08          75.7
2024-11-05 12:00:00                  18.5   13:52:14  14:10:44         112.7
2024-11-05 12:15:00                  38.2   13:13:10  13:51:22          74.4
2024-11-05 12:30:00                   7.8   14:11:41  14:19:29         128.0
2024-11-05 12:45:00                  20.9   14:20:17  14:41:11         100.9
2024-11-05 13:00:00                  23.1   14:42:05  15:05:11          93.9
2024-11-05 13:15:00                   NaN        NaN       NaN           NaN
2024-11-05 13:15:00                   NaN        NaN       NaN           NaN
2024-11-05 13:30:00                  22.7   16:01:21  16:24:03         139.0
2024-11-05 13:30:00                   NaN        NaN       NaN           NaN
2024-11-05 13:45:00                  23.2   15:06:14  15:29:26          99.4
2024-11-05 14:00:00                  30.3   15:30:12  16:00:30         111.4
2024-11-05 14:15:00                   NaN        NaN       NaN           NaN
2024-11-05 14:30:00                  27.4   16:24:52  16:52:16         137.2
2024-11-05 14:45:00                   NaN        NaN       NaN           NaN
2024-11-05 15:00:00                   9.7   16:53:10  17:02:52         117.3
2024-11-05 15:15:00                  14.0   17:03:57  17:17:57         121.8
2024-11-05 15:30:00                   5.2   17:18:47  17:23:59         112.6
2024-11-05 15:30:00                   NaN        NaN       NaN           NaN
2024-11-05 15:45:00                   NaN        NaN       NaN           NaN
2024-11-05 16:00:00                  30.4   17:24:56  17:55:20          89.5
2024-11-05 16:15:00                   4.2   17:56:09  18:00:21         107.2
2024-11-05 16:30:00                   NaN        NaN       NaN           NaN
2024-11-05 16:45:00                  29.8   18:01:10  18:30:58          81.2
2024-11-05 17:00:00                  17.7   18:32:00  18:49:42          82.5
2024-11-05 17:15:00                  17.7   18:50:41  19:08:23          97.2
2024-11-05 17:30:00                  10.3   19:09:15  19:19:33         115.2
2024-11-05 17:45:00                   6.2   19:20:32  19:26:44         104.4

                     patient_id     sex  age age_group        Date  Hour  \
appointment_date
2024-11-05 08:00:00       36264    Male   22     20-24  2024-11-05     8
2024-11-05 08:15:00       35765    Male   27     25-29  2024-11-05     8
2024-11-05 08:30:00       34769  Female   66     65-69  2024-11-05     8
2024-11-05 08:45:00       35873    Male   74     70-74  2024-11-05     8
2024-11-05 09:00:00       35564  Female   77     75-79  2024-11-05     9
2024-11-05 09:00:00       34556  Female   53     50-54  2024-11-05     9
2024-11-05 09:15:00       36536    Male   80     80-84  2024-11-05     9
2024-11-05 09:30:00       11505    Male   55     55-59  2024-11-05     9
2024-11-05 09:45:00       36483    Male   83     80-84  2024-11-05     9
2024-11-05 10:00:00       11833    Male   83     80-84  2024-11-05    10
2024-11-05 10:15:00        3209  Female   42     40-44  2024-11-05    10
2024-11-05 10:30:00       27059    Male   26     25-29  2024-11-05    10
2024-11-05 10:45:00        9503  Female   87     85-89  2024-11-05    10
2024-11-05 11:00:00       27034    Male   60     60-64  2024-11-05    11
2024-11-05 11:15:00       36018    Male   36     35-39  2024-11-05    11
2024-11-05 11:30:00       26292  Female   62     60-64  2024-11-05    11
2024-11-05 11:45:00       25431  Female   70     70-74  2024-11-05    11
2024-11-05 12:00:00       28668  Female   56     55-59  2024-11-05    12
2024-11-05 12:15:00       10116  Female   35     35-39  2024-11-05    12
2024-11-05 12:30:00       22021  Female   56     55-59  2024-11-05    12
2024-11-05 12:45:00        9241    Male   94       90+  2024-11-05    12
2024-11-05 13:00:00       25247  Female   50     50-54  2024-11-05    13
2024-11-05 13:15:00       27895    Male   78     75-79  2024-11-05    13
2024-11-05 13:15:00        2689  Female   76     75-79  2024-11-05    13
2024-11-05 13:30:00       26576  Female   27     25-29  2024-11-05    13
2024-11-05 13:30:00       25046  Female   60     60-64  2024-11-05    13
2024-11-05 13:45:00       36638    Male   75     75-79  2024-11-05    13
2024-11-05 14:00:00       35300  Female   78     75-79  2024-11-05    14
2024-11-05 14:15:00       19921  Female   31     30-34  2024-11-05    14
2024-11-05 14:30:00       35665    Male   73     70-74  2024-11-05    14
2024-11-05 14:45:00       34947  Female   60     60-64  2024-11-05    14
2024-11-05 15:00:00       11005  Female   75     75-79  2024-11-05    15
2024-11-05 15:15:00       19699  Female   54     50-54  2024-11-05    15
2024-11-05 15:30:00       19639  Female   82     80-84  2024-11-05    15
2024-11-05 15:30:00       28449  Female   71     70-74  2024-11-05    15
2024-11-05 15:45:00       15986  Female   64     60-64  2024-11-05    15
2024-11-05 16:00:00       35946    Male   53     50-54  2024-11-05    16
2024-11-05 16:15:00       36353    Male   59     55-59  2024-11-05    16
2024-11-05 16:30:00       36672    Male   53     50-54  2024-11-05    16
2024-11-05 16:45:00       36621    Male   88     85-89  2024-11-05    16
2024-11-05 17:00:00       18113    Male   42     40-44  2024-11-05    17
2024-11-05 17:15:00       36082    Male   82     80-84  2024-11-05    17
2024-11-05 17:30:00       32391  Female   64     60-64  2024-11-05    17
2024-11-05 17:45:00       35422  Female   75     75-79  2024-11-05    17

                     Weekday     Month
appointment_date
2024-11-05 08:00:00  Tuesday  November
2024-11-05 08:15:00  Tuesday  November
2024-11-05 08:30:00  Tuesday  November
2024-11-05 08:45:00  Tuesday  November
2024-11-05 09:00:00  Tuesday  November
2024-11-05 09:00:00  Tuesday  November
2024-11-05 09:15:00  Tuesday  November
2024-11-05 09:30:00  Tuesday  November
2024-11-05 09:45:00  Tuesday  November
2024-11-05 10:00:00  Tuesday  November
2024-11-05 10:15:00  Tuesday  November
2024-11-05 10:30:00  Tuesday  November
2024-11-05 10:45:00  Tuesday  November
2024-11-05 11:00:00  Tuesday  November
2024-11-05 11:15:00  Tuesday  November
2024-11-05 11:30:00  Tuesday  November
2024-11-05 11:45:00  Tuesday  November
2024-11-05 12:00:00  Tuesday  November
2024-11-05 12:15:00  Tuesday  November
2024-11-05 12:30:00  Tuesday  November
2024-11-05 12:45:00  Tuesday  November
2024-11-05 13:00:00  Tuesday  November
2024-11-05 13:15:00  Tuesday  November
2024-11-05 13:15:00  Tuesday  November
2024-11-05 13:30:00  Tuesday  November
2024-11-05 13:30:00  Tuesday  November
2024-11-05 13:45:00  Tuesday  November
2024-11-05 14:00:00  Tuesday  November
2024-11-05 14:15:00  Tuesday  November
2024-11-05 14:30:00  Tuesday  November
2024-11-05 14:45:00  Tuesday  November
2024-11-05 15:00:00  Tuesday  November
2024-11-05 15:15:00  Tuesday  November
2024-11-05 15:30:00  Tuesday  November
2024-11-05 15:30:00  Tuesday  November
2024-11-05 15:45:00  Tuesday  November
2024-11-05 16:00:00  Tuesday  November
2024-11-05 16:15:00  Tuesday  November
2024-11-05 16:30:00  Tuesday  November
2024-11-05 16:45:00  Tuesday  November
2024-11-05 17:00:00  Tuesday  November
2024-11-05 17:15:00  Tuesday  November
2024-11-05 17:30:00  Tuesday  November
2024-11-05 17:45:00  Tuesday  November

In [48]:
print("\nAppointments Every Hour:")
print(df.groupby(df.index.hour).size())

Appointments Every Hour:
appointment_date
8     11150
9     11188
10    11155
11    11167
12    11145
13    11122
14    11137
15    11135
16    11162
17    11127
dtype: int64

In [50]:
# 8. Number of appointments for every weekday
print("\nAppointments Every Weekday:")
print(df.groupby("Weekday").size())

Appointments Every Weekday:
Weekday
Friday       22350
Monday       22293
Thursday     22313
Tuesday      22342
Wednesday    22190
dtype: int64

In [54]:
# 9. Age Group having the highest appointments
print("\nAppointments by Age Group:")
print(df.groupby("age_group").size().sort_values(ascending=False))

Appointments by Age Group:
age_group
75-79    9844
60-64    9649
70-74    9485
65-69    9133
55-59    8955
80-84    8140
50-54    7591
30-34    7527
35-39    7342
40-44    6450
45-49    6152
25-29    5939
85-89    5839
20-24    3984
90+      3068
15-19    2390
dtype: int64

In [52]:
# 10. First and last appointment date
print("\nFirst Appointment :", df.index.min())
print("Last Appointment  :", df.index.max())

First Appointment : 2015-01-01 08:00:00
Last Appointment  : 2024-12-24 17:30:00